import type { Metadata } from "next";
import "./globals.css";
import { Nav } from "@/components/nav";
import { Jua } from "next/font/google";
import { Sidebar } from "@/components/sidebar";

const jua = Jua({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${jua.className}`}>
                <div className="flex">
                    <Sidebar />
                    <div className="w-screen flex flex-col items-center">
                        <Nav />
                        <main className="w-1/2">
                            {children}
                        </main>
                    </div>
                </div>
            </body>
        </html>
    );
}
